apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe-3d-space
  name: fe-3d-space
  namespace: test

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fe-3d-space
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-3d-space
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - image: $IMAGE_NAME
          imagePullPolicy: IfNotPresent
          name: fe-3d-space
          resources:
            limits:
              cpu: '256m'
              memory: 256Mi
            requests:
              cpu: 256m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
