apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe-spaceu-market
  name: fe-spaceu-market
  namespace: test

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fe-spaceu-market
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-spaceu-market
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - image: $IMAGE_NAME
          imagePullPolicy: IfNotPresent
          name: fe-spaceu-market
          resources:
            limits:
              cpu: '1'
              memory: 1024Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
